### ISSUE TITLE
Undo Dice Change, maybe move Dice

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#12]
I intended to close editing the label, but hit dice instead. Tried to undo (three-finger tap to get edit popup menu bar) and undo was not available.

Separately, maybe the dice should be a little further away from close/finish edit? Or move to above the text area only when editing? Or some other way to signal finalize/commit/close editing label.

![PNG image](https://user-images.githubusercontent.com/69103/105131020-fa8ee980-5a9c-11eb-9dda-2c58985a1dff.png)

**Comment by wolfmcnally** [comment]
It seems to me that if you intend to clear the field and hit the Random Name button by accident, it's no tragedy. I can put some more padding between them to minimize fat-fingering.

You can tap anywhere outside the field (except a button) to close editing. In the name field, you can also press the Return key.

**Comment by wolfmcnally** [comment]
![image](https://user-images.githubusercontent.com/676176/105277037-81080180-5b57-11eb-82a3-97e98e28fda5.png)

OK, I've 1) made the buttons bigger. 2) Switched their order so the Clear button is always right-most, and 3) increased the spacing between them.

**Comment by ChristopherA** [comment]
Did you also enable undo in the text field after roll?

**Comment by wolfmcnally** [comment]
No, that's more work and separate from hitting roll accidentally, which I attempted to address above. Feel free to open another issue if it's still important to you.
