### ISSUE TITLE
Import UR SSKR?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#13]
It isn’t clear to me where you import sskr shares via UR QR. Here?

![PNG image](https://user-images.githubusercontent.com/69103/105148554-61210100-5ab7-11eb-97ea-d04fbbe66416.png)

I also like how GW had a universal QR import on Home Screen left that would just do the right thing, sending the QR to the appropriate page. 

![PNG image](https://user-images.githubusercontent.com/69103/105149134-105dd800-5ab8-11eb-88c9-5403244938cc.png)

**Comment by wolfmcnally** [comment]
It would be quite a bit of work to repeatedly scan QRs of ur:crypto-sskr to recompose them. However I did just make a commit so the Import as SSKR function now accepts either shares in ByteWords format or in ur:crypto-sskr format.

**Comment by wolfmcnally** [comment]
For now the only format that is scannable is self-contained: ur:crypto-seed.
