### ISSUE TITLE
Large choices of fonts given non-Dynamic Text

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#2]
![Large for non-dynamic text](https://user-images.githubusercontent.com/69103/103114345-065ccc80-4613-11eb-93e5-3a95bd5e7fca.png)

**Comment by ChristopherA** [comment]
The selection of font size and default UI size choices seem a bit large for me, as if I’m using Dyanamic Text at largest. Makes things feel a little bit less elegant, and if we someday actually do support dynamic text this seems like the largest setting. 

For instance I’m using iPhone 11 Pro Max, and despite this the Notes are just slightly larger than screen. The edit name field can’t support fully showing a name as long as the default names the dice roll, or what can fit in the wrapped title at top.

**Comment by wolfmcnally** [comment]
I was using the `.title` size for the Name field. I have switch to using the `.body` size for it, which is the regular text size.

**Comment by wolfmcnally** [comment]
The size of the title at the top is variable depending on the width of the device, the height of the LifeHash, and the length of the title string.
