### ISSUE TITLE
Long-press LifeHash to copy image to clipboard

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#5]
Not a vital feature, but would make my life easier for documentation and testing:

The ability to long-press a LifeHash and thus copy the image to the clipboard, or long-press on the fingerprint 7 chars to get the full derived SHA1 fingerprint that the LifeHash uses (not the raw data).

Related, I'd love have that for some other normally not copyable items like the hex value. 

I don't see this is a user-facing UX choice with icons and such, but advanced choice mostly for docs and testing. If there is a concern, could be disabled for release versions.

**Comment by wolfmcnally** [comment]
Pretty much everything you can see is now copyable by a long press, including: raw Hex seed data, LifeHashes, Seed Identifiers (all 32 hex bytes), Seed names and, SSKR shares.
