### ISSUE TITLE
SSKR Export needs optional Metadata toggle

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#6]
As we are using CBOR with SSKR, we should offer the option to export the SSKR shares with the metadata (name, notes and birthdate).

**Comment by wolfmcnally** [comment]
Isn't the use-case for SSKR to distribute shares to relatively uninterested parties who have no need for metadata like name, notes, or birthdate? Giving this information to them might leak sensitive information in the notes field, for instance, the names of the other share recipient parties.

**Comment by ChristopherA** [comment]
With sskr the metadata can either be in the Shamir, thus only is visible to the recovering party, so uninterested parties will not see it. That should be the fault.

However there was a requirement from RWOT that some optional metadata could be visible to the shard holders.

**Comment by wolfmcnally** [comment]
I don't see how SSKR can encode any metadata. It isn't designed to do that and has no fields for it. It is designed to split a seed into shares, not as a general message encryption methodology.

**Comment by ChristopherA** [comment]
You are correct. I’d forgotten that sskr encrypted metadata was to be spec’ed by @maaku. a symmetric key was going to be derived from the seed or key encoded in the sskr, and the metadata would be encrypted by that and appended to as a cbor to the sskr, followed by any unencrypted “semi-private” metadata.

**Comment by wolfmcnally** [comment]
I'm going to close this for now; feel free to open a new issue when there is an accepted schema that accomplishes what you want.
