### ISSUE TITLE
System Hard Crash related to sending Screenshots to iCloud Files while in Fehu

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#8]
Not sure how to reproduce this, but will keep an eye out.

Basically taking screenshot in Fehu to illustrate a feature, and the screenshot functionality locked up in it's share sheet to iCloud Files. Was able to eventually get back to Home Screen, then back to Fehu, but it was clunky/slow. I went back to home screen and after a few moments (10 sec?)  it hard crashed with no user interaction.

After reboot, no option to send a test report back to TestFlight.

**Comment by wolfmcnally** [comment]
There is nothing in the app that would interfere with screen shots. There may be a problem with Test Flight offering to send screen shots to the developer, but that is not anything I can fix, although I think it might be possible to disable it for Test Flight distros if necessary.
