### ISSUE TITLE
SSKR Tight

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Fehu#9]
In the UR version of an SSKR, we should offer the option of tight for people like @ksedgwic  that need to put the shares on small metal.

In particular, we don't need `tuna acid epic gyro` when the prefix is ur:crypto-sskr, as that is implied.

**Comment by wolfmcnally** [comment]
If the prefix `ur:crypto-sskr` is present, then the `standard` ByteWords encoding is not used: the CBOR encoding is used with `minimal` Bytewords encoding. This mode is for transmission as URIs or QR codes, and cannot be modified.

If you just export as ByteWords `standard`,  then you can manually drop the first four words if you wish. This is the mode to use for mnemonic and permanent media purposes. The first three words identify this as an SSKR share. The fourth word encodes the length of the share, so if the share is a different length, the third word will not be `gyro`, and in fact may be more than one word if the length is long enough.

In the typical case, a confident user could drop the first **and** last four words, as the last four encode the ByteWords checksum, which is recoverable from the other words if you don't mind losing error detection.

If you're really in a hurry, you can drop the first four words, the last four words, and only engrave the first and last letters of each word. I don't endorse this approach.
